---
- name: Setup hosts
  hosts: k3s_cluster
  pre_tasks:
    - name: Set unique hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
  roles:
    - os
    - xanmanning.k3s
    # - kubecolor
    # - node
    # - kubescape
  # post_tasks:
  # - name: Alias 'k' with kubectl
  #   ansible.builtin.lineinfile:
  #     path: "/home/{{ ansible_user }}/.profile"
  #     line: 'alias k="kubectl"'
