---
- name: Setup hosts
  hosts: k3s_cluster
  pre_tasks:
    - name: Set unique hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
  roles:
    - role: os
      become: true
    - role: xanmanning.k3s
      vars:
        # https://github.com/PyratLabs/ansible-role-k3s#globalcluster-variables
        k3s_become: true
        k3s_etcd_datastore: true
        k3s_server:
          write-kubeconfig-mode: "0644"
          with-node-id: true
          flannel-backend: "wireguard"
        k3s_agent:
          with-node-id: true
        k3s_skip_validation: true
        k3s_skip_env_checks: true
